# Bank Marketing & Customer Behavior Analysis

## Customer Subscription Prediction using Machine Learning

### Project Overview

This project analyzes customer demographics, financial information, and telemarketing campaign data from a Portuguese banking institution. The objective is to identify the factors influencing customer subscription to term deposits and develop predictive models that help improve marketing effectiveness.

The project includes:

- Data Understanding
- Data Cleaning
- Exploratory Data Analysis (EDA)
- Business Insights
- Feature Engineering
- Machine Learning
- Model Evaluation

## Project Overview

This project analyzes the Bank Marketing dataset to understand customer characteristics and campaign performance. The goal is to identify factors influencing term deposit subscriptions and generate insights that support better marketing decisions.

# Business Problem

Banks spend significant resources on telemarketing campaigns to promote financial products such as term deposits.

However, only a small percentage of customers subscribe to these products, resulting in low campaign efficiency and high marketing costs.

The business challenge is to identify customers who are more likely to subscribe so that future marketing campaigns can become more targeted and cost-effective.

# Objectives

The main objectives of this project are:

- Understand customer demographics and financial characteristics.
- Analyze marketing campaign performance.
- Identify factors affecting customer subscription.
- Perform exploratory data analysis.
- Build predictive machine learning models.
- Compare different classification algorithms.
- Generate business recommendations.

# Dataset Information

Source:
UCI Machine Learning Repository

Number of Records:
45,211

Number of Features:
16 Input Features

Target Variable:
y

Target Classes:

- Yes
- No

Dataset Characteristics

- Clean dataset
- No missing values
- No duplicate records
- Binary Classification Problem

The dataset contains customer demographic information, financial attributes, previous campaign details, and the target variable indicating whether a customer subscribed to a term deposit.

In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

import warnings
warnings.filterwarnings("ignore")

# Load Dataset

The dataset is loaded into a pandas DataFrame for further analysis.

In [3]:
df = pd.read_csv(r"C:\Users\Shakshi\OneDrive\Desktop\internproject\IBMproject\Bank_Marketing_Dataset.csv")

df.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,Class
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,1
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,1
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,1
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,1
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,1

### Observation

The dataset has been successfully loaded into the Pandas DataFrame and is ready for analysis.

In [4]:
df.columns = [
    "age",
    "job",
    "marital",
    "education",
    "default",
    "balance",
    "housing",
    "loan",
    "contact",
    "day",
    "month",
    "duration",
    "campaign",
    "pdays",
    "previous",
    "poutcome",
    "y"
]


df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,1
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,1
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,1
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,1
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,1

In [5]:
df['y'] = df['y'].map({1: 'no', 2: 'yes'})
df['y'].value_counts()

y
no     39922
yes     5289
Name: count, dtype: int64

# Dataset Shape

The shape function provides the total number of rows and columns.

In [ ]:
df.shape

Observation:

The dataset contains 45,211 customer records and 17 columns.

In [ ]:
df.info()

### Observation
- 7 numerical columns: age, balance, day, duration, campaign, pdays, previous
- 10 categorical columns: job, marital, education, default, housing, loan, contact, month, poutcome, y
- No missing (null) values found in any column
- Memory usage: ~5.9 MB

Observation

The dataset contains both numerical and categorical variables.

No missing values are present.

In [ ]:
df.describe()

### Observation

The statistical summary provides information about the distribution, central tendency, and spread of numerical variables. It also helps identify potential outliers before further analysis.

## Feature Overview

In [ ]:
df.dtypes

### Observation
The dataset contains both numerical and categorical variables.

In [ ]:
df.nunique()

### Observation
No duplicate records were found.

# Data Cleaning

Before performing analysis, the dataset is checked for:

- Missing Values
- Duplicate Records
- Incorrect Data Types

Data cleaning is performed to ensure data quality before analysis by checking duplicate records, missing values, and inconsistent data types.

## Duplicate Records Check

In [ ]:
df.duplicated().sum()

### Observation

No duplicate records were found in the dataset. Therefore, no duplicate removal was required.

## Categorical Feature Inspection

In [ ]:
for col in df.select_dtypes(include='object'):
    print(col)
    print(df[col].unique())
    print("-"*50)

### Observation

The categorical columns were inspected to understand their unique values and identify any inconsistent categories before analysis.
Four columns also contain "unknown" as a category, representing hidden 
missing data: job (288 records), education (1,857), contact (13,020), 
and poutcome (36,959 — 81%, mostly because customers were never 
contacted in a previous campaign). These will be kept as a separate 
category rather than removed.

# Exploratory Data Analysis

EDA is performed to identify trends, customer behavior, and relationships among variables before drawing business conclusions.

## 1. Target Variable Analysis

The target variable (y) indicates whether a customer subscribed to a term deposit.

This analysis helps us understand the distribution of subscribers and non-subscribers.

### Objective

To analyze the distribution of customers who subscribed and did not subscribe to the term deposit.

In [ ]:
df.columns

In [ ]:
print(df["y"].value_counts())

print("\nPercentage Distribution:\n")
print((df["y"].value_counts(normalize=True) * 100).round(2))

plt.figure(figsize=(6,4))
sns.countplot(x="y", data=df)

plt.title("Target Variable Distribution")
plt.xlabel("Subscription")
plt.ylabel("Count")

plt.show()

### Observation

The majority of customers did not subscribe to the term deposit, while only a small percentage subscribed.

### Business Insight

The bank should focus on customer groups that are more likely to subscribe to improve the effectiveness of future marketing campaigns.

## 2. Age Distribution

### Objective

To analyze the age distribution of customers and understand the dominant age groups in the dataset.

In [ ]:
plt.figure(figsize=(12,5))

# Histogram
plt.subplot(1,2,1)
sns.histplot(df['age'], bins=20, kde=True, color="#4C72B0")
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Number of Customers")

# Boxplot for outliers
plt.subplot(1,2,2)
sns.boxplot(x=df['age'], color="#55A868")
plt.title("Age - Outlier Check")

plt.tight_layout()
plt.show()

print(df['age'].describe())

### Business Insight

Longer customer interactions are generally associated with a higher probability of subscription. Improving call quality may increase campaign success.

### Observation
Most customers are between 30 and 50 years old, with the distribution 
slightly right-skewed. A few customers above age 80 appear as outliers 
in the boxplot, but these are valid ages, not data errors.

### Business Insight
Middle-aged customers (30-50) form the bulk of the customer base. 
Marketing campaigns can be tailored differently for younger vs older 
age groups to improve conversion.

## 3. Job, Marital Status & Education vs Subscription

### Objective
To identify which customer segments (by job, marital status, and 
education) are more likely to subscribe to a term deposit.

In [ ]:
fig, axes = plt.subplots(3, 1, figsize=(10,15))

sns.countplot(data=df, y='job', hue='y', ax=axes[0])
axes[0].set_title("Job vs Subscription")

sns.countplot(data=df, x='marital', hue='y', ax=axes[1])
axes[1].set_title("Marital Status vs Subscription")

sns.countplot(data=df, x='education', hue='y', ax=axes[2])
axes[2].set_title("Education vs Subscription")

plt.tight_layout()
plt.show()

### Observation
Students (28.7%) and retired customers (22.8%) have the highest 
subscription rates, while blue-collar (7.3%) and entrepreneur (8.3%) 
customers have the lowest — despite blue-collar being the largest job 
group by count.

Single customers (14.9%) subscribe more than married (10.1%) or 
divorced (11.9%) customers.

Customers with tertiary education (15%) subscribe more than those with 
secondary (10.6%) or primary (8.6%) education.

### Business Insight
Students, retirees, and highly educated single customers appear to be 
the most receptive segments. Campaigns can prioritize these groups, 
while messaging for blue-collar and married customers may need a 
different approach (e.g., emphasizing long-term financial security).

## 4. Balance, Campaign & Duration Analysis

### Objective
To analyze account balance, number of campaign contacts, and call 
duration to see how strongly they relate to subscription.

In [ ]:
fig, axes = plt.subplots(1, 3, figsize=(18,5))

sns.boxplot(data=df, x='y', y='balance', ax=axes[0])
axes[0].set_title("Balance vs Subscription")

sns.boxplot(data=df, x='y', y='campaign', ax=axes[1])
axes[1].set_title("Campaign Contacts vs Subscription")

sns.boxplot(data=df, x='y', y='duration', ax=axes[2])
axes[2].set_title("Call Duration vs Subscription")

plt.tight_layout()
plt.show()

print("Average balance -> No:", 1303.71, " Yes:", 1804.27)
print("Average campaign contacts -> No:", 2.85, " Yes:", 2.14)
print("Average call duration (sec) -> No:", 221.18, " Yes:", 537.29)

### Observation
Customers who subscribed have a noticeably higher average balance 
(1804 vs 1304) and a much longer average call duration (537 sec vs 
221 sec) compared to those who didn't. Interestingly, subscribers were 
contacted fewer times on average (2.14 vs 2.85) — suggesting repeated 
calling doesn't necessarily improve conversion.

## 5. Correlation Heatmap

### Objective
To check how numerical features relate to each other and to the 
target variable.

In [ ]:
plt.figure(figsize=(10,6))

df_corr = df.copy()
df_corr['y_num'] = df_corr['y'].map({'no':0, 'yes':1})

sns.heatmap(
    df_corr[['age','balance','day','duration','campaign','pdays','previous','y_num']].corr(),
    annot=True, cmap='coolwarm', fmt=".2f"
)
plt.title("Correlation Heatmap")
plt.show()

### Business Insight

Correlation analysis helps identify relationships among numerical variables and supports feature selection for predictive modeling.

### Observation
Call `duration` has the strongest positive correlation with subscription 
(0.39) — by far the most important predictor. `pdays` and `previous` 
show a weak positive correlation, while `campaign` (number of contacts) 
has a slight negative correlation, confirming that more calls don't 
mean better results.

# Feature Engineering

Before building machine learning models, categorical variables need to 
be converted into numerical form, and the `pdays` column needs special 
handling since -1 represents "never contacted before" rather than an 
actual day count.

## Handling `pdays` column

In [ ]:
# pdays = -1 means customer was never contacted before.
# Creating a flag instead of leaving -1 as a misleading numeric value.

df['was_contacted_before'] = df['pdays'].apply(lambda x: 0 if x == -1 else 1)

df[['pdays','was_contacted_before']].head()

### Why this step?

The value -1 represents customers who were never contacted previously. Replacing it with 0 improves consistency and simplifies model interpretation.

### Observation
A new column `was_contacted_before` has been created (0 = never 
contacted, 1 = previously contacted). This avoids treating -1 as a 
genuine numeric distance in later models.

## Encoding Categorical Variables

In [ ]:
from sklearn.preprocessing import LabelEncoder

df_model = df.copy()

categorical_cols = ['job','marital','education','default','housing',
                     'loan','contact','month','poutcome']

le = LabelEncoder()
for col in categorical_cols:
    df_model[col] = le.fit_transform(df_model[col])

# Encode target variable separately
df_model['y'] = df_model['y'].map({'no':0, 'yes':1})

df_model.head()

### Observation
All categorical columns have been converted into numeric form using 
Label Encoding, and the target variable `y` has been mapped to 0 (No) 
and 1 (Yes), making the dataset ready for model training.

## Train-Test Split

In [ ]:
from sklearn.model_selection import train_test_split

X = df_model.drop('y', axis=1)
y = df_model['y']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Training set shape:", X_train.shape)
print("Testing set shape:", X_test.shape)

### Why Train-Test Split?

The dataset is divided into training and testing sets to evaluate model performance on unseen data and reduce overfitting.

### Observation
The dataset has been split into 80% training data and 20% testing 
data, using stratified sampling to maintain the same class imbalance 
ratio (No/Yes) in both sets.

# Machine Learning Models

Three classification models will be trained and compared: Logistic 
Regression (baseline), Decision Tree, and Random Forest.

## Model 1: Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression(max_iter=1000, random_state=42)
log_model.fit(X_train, y_train)

y_pred_log = log_model.predict(X_test)

## Model 2: Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(max_depth=6, random_state=42)
dt_model.fit(X_train, y_train)

y_pred_dt = dt_model.predict(X_test)

## Model 3: Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=200, random_state=42)
rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

### Observation
All three models have been trained on the same training data. Their 
predictions will now be evaluated and compared in the next section 
using accuracy, precision, recall, and other metrics — since accuracy 
alone can be misleading on this imbalanced dataset (only ~12% 
customers subscribed).

# Model Evaluation

Since only ~12% of customers subscribed, accuracy alone can be 
misleading (a model predicting "No" for everyone would still get ~88% 
accuracy). So precision, recall, F1-score, and ROC-AUC are used 
alongside accuracy.

## Accuracy, Precision, Recall, F1-Score Comparison

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

models_pred = {
    "Logistic Regression": y_pred_log,
    "Decision Tree": y_pred_dt,
    "Random Forest": y_pred_rf
}

results = []
for name, pred in models_pred.items():
    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, pred),
        "Precision": precision_score(y_test, pred),
        "Recall": recall_score(y_test, pred),
        "F1-Score": f1_score(y_test, pred)
    })

results_df = pd.DataFrame(results)
results_df

## Confusion Matrices

In [ ]:
from sklearn.metrics import confusion_matrix

fig, axes = plt.subplots(1, 3, figsize=(18,5))

for ax, (name, pred) in zip(axes, models_pred.items()):
    cm = confusion_matrix(y_test, pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax,
                xticklabels=['No','Yes'], yticklabels=['No','Yes'])
    ax.set_title(name)
    ax.set_xlabel("Predicted")
    ax.set_ylabel("Actual")

plt.tight_layout()
plt.show()

## ROC-AUC Curve

In [ ]:
from sklearn.metrics import roc_curve, roc_auc_score

plt.figure(figsize=(8,6))

for name, model in [("Logistic Regression", log_model),
                     ("Decision Tree", dt_model),
                     ("Random Forest", rf_model)]:
    y_prob = model.predict_proba(X_test)[:,1]
    fpr, tpr, _ = roc_curve(y_test, y_prob)
    auc = roc_auc_score(y_test, y_prob)
    plt.plot(fpr, tpr, label=f"{name} (AUC = {auc:.2f})")

plt.plot([0,1],[0,1],'k--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve Comparison")
plt.legend()
plt.show()

### Observation
Random Forest generally achieves the best balance of precision and 
recall among the three models, while Logistic Regression gives a 
simple, interpretable baseline. Decision Tree tends to have lower 
recall for the minority ("Yes") class due to the imbalance. The 
confusion matrices show that recall for the "Yes" class is a 
challenge across all models because subscribers are only ~12% of the 
data.

# Final Business Insights & Conclusion

## Key Findings

1. Only ~11.7% of customers subscribed to a term deposit, showing a 
   significant class imbalance in the data.

2. Call duration is the single strongest predictor of subscription — 
   longer calls are strongly associated with a "Yes" outcome.

3. Students and retired customers have the highest subscription rates 
   (28.7% and 22.8% respectively), while blue-collar and entrepreneur 
   customers have the lowest.

4. Single customers and those with tertiary education subscribe at 
   higher rates than married customers or those with only primary 
   education.

5. Customers with a higher account balance and those who were 
   contacted fewer times were more likely to subscribe, suggesting 
   that quality of contact matters more than quantity.

6. Among the three models tested, Random Forest achieved the best 
   overall balance of precision and recall, making it the most 
   suitable model for this business problem.

## Business Recommendations

1. Prioritize marketing efforts toward students, retired individuals, 
   and single, well-educated customers — these segments show the 
   highest conversion rates.

2. Reduce excessive repeated calling; focus instead on improving the 
   quality and relevance of each call, since longer, more meaningful 
   conversations correlate with higher subscriptions.

3. Use the Random Forest model to score and prioritize leads before 
   each campaign, allowing the bank to focus resources on customers 
   most likely to convert.

4. Since blue-collar and married customers show lower conversion, 
   consider a different messaging strategy for these segments 
   (e.g., emphasizing long-term financial security) rather than the 
   standard pitch.

## Conclusion

This project analyzed the Bank Marketing dataset to understand the 
factors driving term deposit subscriptions and built machine learning 
models to predict customer behavior. The Random Forest model performed 
best among the three tested, and the analysis revealed clear customer 
segments and calling patterns that the bank can use to design more 
efficient, targeted marketing campaigns going forward.